#cursor
use excelr;



   #TRIGGERS
  #BEFORE INSERT 
CREATE TABLE EMP1(ID INT,NAME VARCHAR(50),WORKING_HRS INT);
INSERT INTO EMP1 VALUES (1,"RAM",50);
INSERT INTO EMP1 VALUES(2,"RAMYA",-40);
INSERT INTO EMP1 VALUES(2,"RAMYA",-50);
  SELECT *FROM EMP1;
  
  use excelr;
  show tables;
  
#AFTER INSERT
CREATE TABLE EMP2(ID INT,NAME VARCHAR(40),AGE INT);
  CREATE TABLE EMP_AUDITT(ID INT,AUDIT_DESC VARCHAR(50));
  INSERT INTO EMP2 VALUES(1,"AKASH",25);
  INSERT INTO EMP2 VALUES(2,"AKA",26);
  INSERT INTO EMP2 VALUES(3,"AKA",26);
  SELECT *FROM EMP_AUDITT;	
  SELECT *FROM EMP2;
  
  
  
    #BEFORE UPDATE
  CREATE TABLE PRODUCT(ID INT,NAME VARCHAR(40),COST DECIMAL(8,2));
  INSERT INTO PRODUCT VALUES(1,"MOB1",10000),(2,"MOB2",14000),(3,"MOB3",18000);
  insert into product values(4,"mob4",30000);
  SELECT *FROM PRODUCT;
  update product set cost=COST+30000 where id IN(1);
  set sql_safe_updates=0;
  
  
  
  
  #AFTER UPDATE
SELECT *FROM BOOKS;
SELECT *FROM BOOK_SALES;

desc books;

#ALTER TABLE FOR AFTER UPDATE
ALTER TABLE BOOKS ADD COLUMN SALES INT DEFAULT 0;
UPDATE BOOKS SET SALES=SALES+2 WHERE BOOKID=1;
SELECT *FROM BOOKS;
SELECT *FROM BOOK_SALES;




#BEFORE DELETE
 CREATE TABLE EMP(EMP_ID INT,HIRE_DATE DATE,SALARY INT);
 INSERT INTO EMP VALUES(1,"2022-01-02",20000),(2,"2023-03-10",30000),(3,"2021-09-11",50000);
 INSERT INTO EMP VALUES(4,"2023-01-02",80000),(5,"2022-03-10",70000),(6,"2020-09-11",60000);
 SELECT *FROM EMP;
  
CREATE TABLE BACKUP(ID INT PRIMARY KEY AUTO_INCREMENT,
EMP_ID INT,HIRE_DATE DATE,SALARY INT,DELETED_AT TIMESTAMP DEFAULT NOW());

DELETE FROM emp WHERE EMP_ID=4;
SELECT *FROM BACKUP;





#AFTER DELETE
 CREATE TABLE EMP_SALARYY(EMP_ID INT,EMP_NAME VARCHAR(50),SALARY DECIMAL(10,3)); 
 INSERT INTO EMP_SALARYY VALUES(1,"RAM",30000),(2,"SWATHI",40000);
 INSERT INTO EMP_SALARYY VALUES(3,"RAM",50000),(4,"SWATHI",60000);
  SELECT *FROM EMP_SALARYY;
  
  CREATE TABLE BUDGETT(TOTAL DECIMAL(10,2));
  INSERT INTO BUDGETT(TOTAL) SELECT SUM(SALARY) FROM EMP_SALARYY;
  SELECT *FROM BUDGETT;
  DELETE FROM EMP_SALARYY WHERE EMP_ID=2;
  SELECT *FROM BUDGETT;
  
   # STORED PROCEDURE:
UPDATE BUDGETT SET TOTAL=TOTAL-OLD.SALARY;
  
  