/* STORED PROCEDURE = IT IS USED TO STORE THE QUERY PHYSICALLY IN THE DATABASE

BIG SCENARIOS ARE STORES UNDER STORED PROCEDURE
IN SP-PARAMETERS,LOOPS,ERROR HANDLING ,CURSOR,TRIGGERS

SP ARE USED TO RUN TO GENERATE DAILY,WEEKLY,MONTHLY,QUARTERLY,YEARLY ETC REPORTS */

#MAINLY FOR EXPRENCEIED NOT PREFERED FOR THE FRESHERS 

call DEP60();

CALL AGGREGATED_CALS();

/* PARAMETERS
1.IN -BASED ON INPUT
2.OUT -STROING THE OUTPUT IN A VARIABLE
3.INOUT -COMBINATION OF INPUT VALUE AND OUTPUT

NAME THE PARAMETERS IN STORED PROCEDURE [IMPORTANT FOR  FRESHERS]

*/

#call function is used to execute the stored procedures

DELIMITER //#this is the syntax of the stored procedure
  CREATE PROCEDURE `new_procedure` ()
  BEGIN
  
  END //
  DELIMITER ;

call input1(105);

DELIMITER //
  CREATE PROCEDURE `INPUT2` (IN DID INT)
  BEGIN
  
  SELECT *FROM MYEMP WHERE DEP_ID=DID;
  
  END //
  DELIMITER ;
  
  
  
     
  
  DELIMITER //
  CREATE PROCEDURE `INPUT3` (IN a INT,IN b INT)
  BEGIN
  
select * from myemp where SALARY BETWEEN A AND B;
     
  END //
  DELIMITER ;
  
  CALL INPUT3(100,200);
  
  
  
  #SALES DATABASE
  USE SALES;
  select * from orders;
  show databases;
#FIND THE COUNTRY WISE TOTAL SALES,TOTAL PROFIT WITH DHYNAMIC FILTER ON YEAR

  DELIMITER //
  CREATE PROCEDURE `country_sales` (IN yr varchar(6) )
  BEGIN  
  select country,
         sum(sales) as total_sales,
         sum(profit) as total_profit
         from orders
         where year(Order_Date)=2020
         group by country;
     
  END //
  DELIMITER ;
  
  
#FIND THE year wise DYNAMIC TOPN STATE WISE TOTAL SALES

DELIMITER //
  CREATE PROCEDURE `STATE_TOPN` ( IN yr varchar(6),
                            in TOPN INT)
  BEGIN
select state,
       sum(sales) as total_sales
       from orders
       where year(`order_date`)=yr
       group by state
       ORDER BY sum(sales) DESC
       limit TOPN;
     
  END //
  DELIMITER ;
  
  CALL STATE_TOPN(2020,3);  
  
  
#FIND THE SALES BETWEEN DATE RANGES


DELIMITER //
  CREATE PROCEDURE `DATE_RANGE` ( IN START_DATE DATE,
                                   IN END_DATE DATE)
BEGIN
SELECT *FROM ORDERS WHERE ORDER_DATE BETWEEN START_DATE AND END_DATE;

 END //
  DELIMITER ;
  
  
#GET THE SALES GREATER THAN  DYNAMIC NUMBER AND YEAR WISE AND COUNTRY WISE SALES
  
  
  DELIMITER //
  CREATE PROCEDURE `SALES_CTY_YR` (IN YR VARCHAR(10),IN CTR VARCHAR(20),IN NUM1 INT,IN NUM2 INT)
  BEGIN
  
SELECT YEAR(ORDER_DATE),COUNTRY,COUNT(SALES) FROM ORDERS
WHERE YEAR(ORDER_DATE)=YR AND COUNTRY=CTR AND SALES>NUM1 AND SALES<NUM2;
     
  END //
  DELIMITER ;


USE EXCELR;

#OUTPUT PARAMETER


     
  
  DELIMITER //
  CREATE PROCEDURE `output1` (out SAL INT)
BEGIN

SELECT SUM(SALES) INTO SAL FROM MYEMP;  
  END //
  DELIMITER ;
  
  #TO KNOW THE OUTPUT
  
  CALL output1(@SAL);
  SELECT @SAL;
  
  SELECT EMP_ID,FIRST_NAME ,SALARY,@SAL FROM myemp;
  SELECT * FROM MYEMP;
  
  
    DELIMITER //
  CREATE PROCEDURE `output2` (out SAL INT,OUT MX INT,OUT MN INT,OUT AVG INT)
BEGIN

SELECT SUM(SALES),MAX(sales),MIN(sales),avg(SALES) INTO SAL,MX,MN,AVG FROM MYEMP;  
  END //
  DELIMITER ;
  
	